FROM node:22.17.1-alpine AS build
RUN corepack enable && corepack prepare pnpm@10.30.3 --activate
WORKDIR /app

COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm -C packages/db run generate
RUN pnpm -C apps/api build

FROM node:22.17.1-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app /app

EXPOSE 3000
CMD ["node", "apps/api/dist/main.js"]
