apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sb-ledger-api
  namespace: sb-ledger
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
