apiVersion: v1
kind: Secret
metadata:
  name: sb-ledger-secret
  namespace: sb-ledger
type: Opaque
stringData:
  POSTGRES_PASSWORD: "ledger"
  DATABASE_URL: "postgresql://ledger:ledger@postgres:5432/ledger?schema=public"
