apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: sb-ledger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: sb-ledger-worker:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9100
          env:
            - name: METRICS_PORT
              value: "9100"
            - name: METRICS_REFRESH_MS
              value: "2000"
            - name: VERSION
              valueFrom: { configMapKeyRef: { name: sb-ledger-config, key: VERSION } }
            - name: SERVICE_NAME
              valueFrom: { configMapKeyRef: { name: sb-ledger-config, key: SERVICE_NAME_WORKER } }
            - name: DATABASE_URL
              valueFrom: { secretKeyRef: { name: sb-ledger-secret, key: DATABASE_URL } }
            - name: KAFKA_BROKER
              valueFrom: { configMapKeyRef: { name: sb-ledger-config, key: KAFKA_BROKER } }
            - name: REDIS_HOST
              valueFrom: { configMapKeyRef: { name: sb-ledger-config, key: REDIS_HOST } }
            - name: REDIS_PORT
              valueFrom: { configMapKeyRef: { name: sb-ledger-config, key: REDIS_PORT } }
            - name: CASHBACK_RULE_CACHE_TTL_SECONDS
              value: "60"
            - name: CASHBACK_RULE_CACHE_LOCK_MS
              value: "300"
            - name: CASHBACK_RULE_CACHE_WAIT_MS
              value: "30"

            - name: EVENT_TOPIC
              valueFrom: { configMapKeyRef: { name: sb-ledger-config, key: EVENT_TOPIC } }
            - name: DLQ_TOPIC
              valueFrom: { configMapKeyRef: { name: sb-ledger-config, key: DLQ_TOPIC } }
            - name: CONSUMER_GROUP
              valueFrom: { configMapKeyRef: { name: sb-ledger-config, key: CONSUMER_GROUP } }

            - name: POLL_INTERVAL_MS
              valueFrom: { configMapKeyRef: { name: sb-ledger-config, key: POLL_INTERVAL_MS } }
            - name: BATCH_SIZE
              valueFrom: { configMapKeyRef: { name: sb-ledger-config, key: BATCH_SIZE } }
            - name: MAX_ATTEMPTS
              valueFrom: { configMapKeyRef: { name: sb-ledger-config, key: MAX_ATTEMPTS } }
            - name: RETRY_POLL_INTERVAL_MS
              valueFrom: { configMapKeyRef: { name: sb-ledger-config, key: RETRY_POLL_INTERVAL_MS } }
            - name: RETRY_BATCH_SIZE
              valueFrom: { configMapKeyRef: { name: sb-ledger-config, key: RETRY_BATCH_SIZE } }
